; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=XML Viewer
AppVersion=2.0
DefaultDirName={pf}\XML Viewer
DefaultGroupName=XML Viewer

[Files]
Source: "E:\Учёба\Практика по пр\Les27-28\Task1\bin\Release\XML Viewer.exe"; DestDir: "{app}"

[Icons]
Name: "{group}\XML Viewer"; Filename: "{app}\XMLViewer.exe"; WorkingDir: "{app}"; IconFilename: "{app}\XMLicon.png"


